### PR TITLE
Added conditionals in scribbler_tags.py and views.py to handle …

### PR DESCRIPTION
**Pull request by benred42**
…multiple template engines.  Might not be necessary for next release and certainly could use some proper testcases, but this should work in the event that other template engines in addition to DjangoTemplates are enabled.

### CODE REVIEW

**Comment by mlavin** [comment]
It would be possible to include multiple template engines in the `runtests.py` as well as test with invalid/incorrect `TEMPLATES` settings via `override_settings`.

**Comment by benred42** [comment]
Build failure addressed in #95 . I added the jinja2 dependency to tox.ini there to keep the tox changes to a single PR.

**Comment by benred42** [comment]
Okay, the reason the Python3.2/Django1.8 test fail is because the latest versions of Jinja2 are incompatible with Python<3.2.  This can be solved by using Jinja2.6 for that testenv.

**Comment by mlavin** [comment]
:rabbit:

**Pull request merged**
