### PR TITLE
remove deprecated string arguments to url()

### PR DESCRIPTION
**Pull request by tobiasmcnulty**

### CODE REVIEW

**Comment by mlavin** [comment]
`patterns` is deprecated as well and should be removed. This can just be a list or tuple.

**Comment by tobiasmcnulty** [comment]
@mlavin There are a number of pending deprecation warnings in 1.7 and 1.8, including some in templates, but I'm not sure any of them can be resolved (including ``urlpatterns``) without testing ``django.VERSION`` -- is that something you want to introduce?

I like the import change because it works in all versions of Django and creates better error messages when there is a problem, too.

**Comment by mlavin** [comment]
The use of `patterns` has never been required in any version of Django.

**Comment by mlavin** [comment]
My vote would be to drop support for everything < 1.7. I know 1.4 is still supported by Django but until the new deprecation policy/timeline is in place it isn't feasible to support LTS -> LTS.

**Comment by tobiasmcnulty** [comment]
:sleeping: of course!

I will say I think it's perfectly reasonable to support 1.4 -> 1.8 -- we are basically doing it already.

**Comment by mlavin** [comment]
:rocket:

**Pull request merged**
