### PR TITLE
116 drop south

### PR DESCRIPTION
**Pull request by dchukhin**
#116 
Since we are no longer using South, remove the South migrations, and their mention from the documentation.

### CODE REVIEW

**Comment by mlavin** [comment]
aaaah I just added the same PR!

**Comment by mlavin** [comment]
Looks like we updated different parts of the docs. I think these can both be merged without conflict.

**Comment by dchukhin** [comment]
:+1:

**Comment by dchukhin** [comment]
good job with the docs that I had forgotten

**Pull request merged**
